### ISSUE TITLE
akka.cluster.http.management.hostname should be InetAddress.getLocalHost.getHostAddress() 

### ISSUE THREAD

**Issue by sebastianharko** [akka/akka-cluster-management#11]
I think that akka.cluster.http.management.hostname should resolve to a call to InetAddress.getLocalHost.getHostAddress() if it's left empty (""). 

Akka Remoting already does this when "..remote.netty.hostname" is left empty ""  (see: [here](https://github.com/akka/akka/blob/master/akka-remote/src/main/resources/reference.conf#L446))

**Comment by sebastianharko** [comment]
I can do a PR for this if you guys consider this to be a good idea :-)

**Comment by patriknw** [comment]
Sounds good

**Comment by 2m** [comment]
Fixed in #13
