### ISSUE TITLE
decouple "backend" from frontend (akka-http)

### ISSUE THREAD

**Issue by sebastianharko** [akka/akka-cluster-management#12]
It would be nice to have a better decoupling before the "backend" logic and the akka-http frontend.  Some people may want to use a different web front-end (http4s, Spring MVC etc.) but get the same info about members etc. Like all problems in CS, this can be solved by another level of indirection. In this case, introducing a controller class ... 

EDIT: I offer to do a PR for this, if it's considered a decent idea

**Comment by patriknw** [comment]
Is it really worth it? How many lines of code would it actually save? 

It's not strange that we are opinionated about using Akka HTTP for this utility.

**Comment by ktoso** [comment]
I don't think we should spend the time on this, sorry @sebastianharko.
We're the Akka team, this is the Akka organisation, and it uses Akka HTTP to manage Akka Cluster...
It makes sense. 

If someone indeed from-the-field will really need this we can reconsider, but let's not complicate more than we need to.
